services:
  - docker

script:
  - docker run -v "$TRAVIS_BUILD_DIR:/go/src/github.com/Webstrates/golem-herder" -w "/go/src/github.com/Webstrates/golem-herder" golang:1.8 go build -o golem-herder main.go
  - sudo chmod +x golem-herder

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t webstrates/golem-herder:latest .;
    docker push webstrates/golem-herder:latest;
    fi
